### ISSUE TITLE
Projects section

### ISSUE THREAD

**Issue by cwaku** [cwaku/portfolio#19]
- Add projects section
  - homepage
  - projects page

**Comment by KunalSin9h** [comment]
@cwaku can you elaborate on this issue a bit more? 
I am not able to understand clearly.

**Comment by cwaku** [comment]
> @cwaku can you elaborate on this issue a bit more? I am not able to understand clearly.

@KunalSin9h  I am looking to add projects to that section but I am not decisive on what design to use. I'd appreciate if you could build that with dummy project data.

**Comment by KunalSin9h** [comment]
now understand

**Comment by RohithBoppey** [comment]
You can take a look at my portfolio: https://rohithboppey.netlify.app

This is the homepage
![image](https://user-images.githubusercontent.com/73538974/183085952-a8f0bef6-dc55-44a3-8683-b2a6ef9c416c.png)

This is the project section: 
![image](https://user-images.githubusercontent.com/73538974/183086055-68590454-c39a-4331-81b7-7a15bbc9f9af.png)

**Comment by cwaku** [comment]
@RohithBoppey That's nice. I love the animation on there. Your portfolio looks great btw 💯

**Comment by RohithBoppey** [comment]
> @RohithBoppey That's nice. I love the animation on there. Your portfolio looks great btw 💯 

But it's using tailwind css. I think you are using MUI.

**Comment by dontdude** [comment]
I am using GitHub API, to only show my starred projects. 
Have a look : [https://portfolio-dontdude.vercel.app/](url)
![Screenshot 2022-09-04 185643](https://user-images.githubusercontent.com/75321407/188315956-e456ce48-0a8a-4359-b78f-cbfe0a68a3b3.png)

**Comment by cwaku** [comment]
@dontdude I also used the GitHub API to fetch the projects instead of creating my own backend. Thanks for the tip
